/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package delfitree;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.File;

class TreeParserTest {
    @Test
    void testMakeTree()
    {
        File dir = new File("src/test/resources/");
        TreeParser parser = new TreeParser(dir);

        Forest nodes = parser.makeTree(IncludeType.None, "", "");
        assertEquals(7, nodes.size());
        for (Node node : nodes) {
            assertEquals(node.getIfaceUses().size(), 0);
            assertEquals(node.getImplUses().size(), 0);
        }

        nodes = parser.makeTree(IncludeType.Interface, "", "");
        assertEquals(7, nodes.size());
        assertEquals(2, nodes.getNodeByName("uCEFSchemeRegistrar").getIfaceUses().size());
        assertEquals(0, nodes.getNodeByName("uCEFSchemeRegistrar").getImplUses().size());

        nodes = parser.makeTree(IncludeType.Implementation, "", "");
        assertEquals(7, nodes.size());
        assertEquals(0, nodes.getNodeByName("uCEFSchemeRegistrar").getIfaceUses().size());
        assertEquals(1, nodes.getNodeByName("uCEFSchemeRegistrar").getImplUses().size());

        nodes = parser.makeTree(IncludeType.Both, "", "");
        assertEquals(7, nodes.size());
        assertEquals(2, nodes.getNodeByName("uCEFSchemeRegistrar").getIfaceUses().size());
        assertEquals(1, nodes.getNodeByName("uCEFSchemeRegistrar").getImplUses().size());
        assertEquals(7, nodes.getNodeByName("uCEFApp").getIfaceUses().size());
        assertEquals(0, nodes.getNodeByName("uCEFApp").getImplUses().size());

        nodes = parser.makeTree(IncludeType.Both, "uCEF", "");
        assertEquals(2, nodes.getNodeByName("uCEFSchemeRegistrar").getIfaceUses().size());
        assertEquals(1, nodes.getNodeByName("uCEFSchemeRegistrar").getImplUses().size());
        assertEquals(4, nodes.getNodeByName("uCEFApp").getIfaceUses().size());
        assertEquals(0, nodes.getNodeByName("uCEFApp").getImplUses().size());

        nodes = parser.makeTree(IncludeType.Both, "uCEF", "uCEFApplicationCore");
        assertEquals(6, nodes.size());
    }
}
